theme: jekyll-theme-midnight
title: âœ¿ Welcome to my Personal Portfolio âœ¿
description: ðŸ“Š I am  Eirini Nterou and this is my GitHub Pages site with some Data Analytics projects that I worked on.
